DESCRIPTION = "Linux kernel for OrangePi 4 LTS"

inherit kernel
inherit python3native
require recipes-kernel/linux/linux-yocto.inc

DEPENDS += "openssl-native u-boot-tools-native"

SRC_URI = " \
	git://github.com/orangepi-xunlong/linux-orangepi;branch=orange-pi-5.10-rk35xx; \
	file://brcmfmac.scc \
"

SRCREV = "${AUTOREV}"
LINUX_VERSION = "5.10.160"
KCONFIG_MODE = "alldefconfig"

LIC_FILES_CHKSUM = "file://COPYING;md5=6bc538ed5bd9a7fc9398086aedcd7e46"

# Override local version in order to use the one generated by linux build system
# And not "yocto-standard"
LINUX_VERSION_EXTENSION = ""
PR = "r1"
PV = "${LINUX_VERSION}"

# Include only supported boards for now
COMPATIBLE_MACHINE = "(rk3566)"

do_compile_append() {
	oe_runmake dtbs
}

# Make sure we use /usr/bin/env ${PYTHON_PN} for scripts
do_patch_append() {
	for s in `grep -rIl python ${S}/scripts`; do
		sed -i -e '1s|^#!.*python[23]*|#!/usr/bin/env ${PYTHON_PN}|' $s
	done
}

do_deploy_append() {
	install -d ${DEPLOYDIR}/overlays
	install -m 644 ${B}/arch/arm64/boot/dts/rockchip/overlay/* ${DEPLOYDIR}/overlays
	# install -m 644 ${S}/arch/arm64/boot/dts/rockchip/overlays-orangepi4/hw_intfc.conf ${DEPLOYDIR}/
}
